// <auto-generated />
using System;
using MCards.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MCards.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191204104058_users")]
    partial class users
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MCards.Entities.Card", b =>
                {
                    b.Property<int>("PK_Card")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardName");

                    b.Property<int>("CardNumber");

                    b.Property<int>("FK_CardType");

                    b.Property<int>("FK_Condition");

                    b.Property<int>("FK_Expansion");

                    b.Property<bool>("IsFoil");

                    b.HasKey("PK_Card");

                    b.HasIndex("FK_CardType");

                    b.HasIndex("FK_Expansion");

                    b.ToTable("Card");
                });

            modelBuilder.Entity("MCards.Entities.CardType", b =>
                {
                    b.Property<int>("PK_CardType")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardTypeName");

                    b.HasKey("PK_CardType");

                    b.ToTable("CardType");
                });

            modelBuilder.Entity("MCards.Entities.Expansion", b =>
                {
                    b.Property<int>("PK_Expansion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ExpansionCards");

                    b.Property<string>("ExpansionName");

                    b.Property<string>("ExpansionShortName");

                    b.HasKey("PK_Expansion");

                    b.ToTable("Expansion");
                });

            modelBuilder.Entity("MCards.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MCards.Entities.Card", b =>
                {
                    b.HasOne("MCards.Entities.CardType", "CardType")
                        .WithMany()
                        .HasForeignKey("FK_CardType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MCards.Entities.Expansion", "Expansion")
                        .WithMany()
                        .HasForeignKey("FK_Expansion")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
